*
* Token codes
*
*[Category Flags (4 bits) ] [ Sub-category Flags (4 bits) ] [ Token Value (8 bits)]
* Bit Index: 15 14 13 12   | 11 10  9  8   |   7  6  5  4  3  2  1  0
*
* Major Category Bit Patterns (Bits 15-12)
C_OPER      GEQU    $0
C_FLOW      GEQU    $1000
C_DATA_TYPE GEQU    $2000
C_KEYWORD   GEQU    $3000

C_LITERAL   GEQU    $4000
S_INT       GEQU    $0000
S_FLOAT     GEQU    $0100
S_STRING    GEQU    $0200
T_STRING    GEQU    $4301


C_SPECIAL   GEQU    $5000
C_LOGICAL   GEQU    $6000
C_COMPARE   GEQU    $7000
C_ASSIGN    GEQU    $8000
C_BITWISE   GEQU    $9000
C_ACCESS    GEQU    $A000
C_PREPROCES GEQU    $B000
C_COMMENTS  GEQU    $C000
C_BRACKETS  GEQU    $D000
C_SEPDELIMS GEQU    $E000
C_RESERVED  GEQU    $F000

T_AUTO      GEQU    $1
T_BREAK     GEQU    $2
T_CASE      GEQU    $3
T_CHAR      GEQU    $4
T_CONST     GEQU    $5
T_CONTINUE  GEQU    $6
T_DEFAULT   GEQU    $7
T_DO        GEQU    $8
T_DOUBLE    GEQU    $9
T_ELSE      GEQU    $A
T_ENUM      GEQU    $B
T_EXTERN    GEQU    $C
T_FLOAT     GEQU    $D
T_FOR       GEQU    $E
T_GOTO      GEQU    $F
T_IF        GEQU    $10
T_INT       GEQU    $11
T_LONG      GEQU    $12
T_REGISTER  GEQU    $13
T_RETURN    GEQU    $14
T_SHORT     GEQU    $15
T_SIGNED    GEQU    $16
T_SIZEOF    GEQU    $17
T_STATIC    GEQU    $18
T_STRUCT    GEQU    $19
T_SWITCH    GEQU    $1A
T_TYPEDEF   GEQU    $1B
T_UNION     GEQU    $1C
T_UNSIGNED  GEQU    $1D
T_VOID      GEQU    $1E
T_VOLATILE  GEQU    $1F
T_WHILE     GEQU    $20
T_PLUS      GEQU    $21
T_DASH      GEQU    $22
T_STAR      GEQU    $23
T_LPAREN    GEQU    $24
T_RPAREN    GEQU    $25
T_DIV       GEQU    $26
T_MOD       GEQU    $27
T_PLUSPLUS  GEQU    $28
T_DASHDASH  GEQU    $29
T_DOT       GEQU    $2A
T_EQUAL     GEQU    $2B
T_PLUSEQUAL GEQU    $2C
T_DASHEQUAL GEQU    $2D
T_STAREQUAL GEQU    $2E
T_DIVEQUAL  GEQU    $2F
T_MODEQUAL  GEQU    $30
T_EQEQ      GEQU    $31
T_GREATER   GEQU    $32
T_LESSTHAN  GEQU    $33
T_BANG      GEQU    $34
T_NOTEQUAL  GEQU    $35
T_GTEQUAL   GEQU    $36
T_LTEQUAL   GEQU    $37
T_AND       GEQU    $38
T_ANDAND    GEQU    $39
T_BAR       GEQU    $3A
T_BARBAR    GEQU    $3B
T_CARET     GEQU    $3C
T_TILDE     GEQU    $3D
T_LSHIFT    GEQU    $3E
T_RSHIFT    GEQU    $3F
T_COMMA     GEQU    $40
T_COLON     GEQU    $41
T_TERNARY   GEQU    $42
T_LBRACKET  GEQU    $43
T_RBRACKET  GEQU    $44
T_LCURLY    GEQU    $45
T_RCURLY    GEQU    $44
T_HASH      GEQU    $45
T_DEREF     GEQU    $46
T_NUMBER    GEQU    $47
T_IDENT     GEQU    $48
T_SEMI      GEQU    $49
T_ANDEQUAL  GEQU    $50
T_BAREQUAL  GEQU    $51
T_CARETEQ   GEQU    $52
T_BACKSLASH GEQU    $53
T_DBLQUOTE  GEQU    $54
T_SNGQUOTE  GEQU    $55
T_STARTCMT  GEQU    $56
T_ENDCMT    GEQU    $57
T_LINECMT   GEQU    $58

